name: work.efiz.near

x-pg-common: &pg-common
  image: postgres:17-alpine
  environment: &pg-env
    POSTGRES_USER: everythingdev
    POSTGRES_PASSWORD: everythingdev
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U everythingdev"]
    interval: 3s
    timeout: 3s
    retries: 5

services:
  postgres-api:
    <<: *pg-common
    container_name: work.efiz.near-postgres-api
    environment:
      <<: *pg-env
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - work_efiz_near_postgres_api_data:/var/lib/postgresql/data

  postgres-auth:
    <<: *pg-common
    container_name: work.efiz.near-postgres-auth
    environment:
      <<: *pg-env
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - work_efiz_near_postgres_auth_data:/var/lib/postgresql/data

volumes:
  work_efiz_near_postgres_api_data:
    name: work_efiz_near_postgres_api_data
  work_efiz_near_postgres_auth_data:
    name: work_efiz_near_postgres_auth_data
